version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: deepscraper
      POSTGRES_USER: deepscraper
      POSTGRES_PASSWORD: deepscraper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2023-12-14T18-51-57Z
    environment:
      MINIO_ROOT_USER: deepscraper
      MINIO_ROOT_PASSWORD: deepscrapersecret
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  app:
    build: .
    command: poetry run uvicorn deepscraper.web.api:app --host 0.0.0.0 --port 8000
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - minio

volumes:
  postgres_data:
  minio_data:
